# Generated by Django 4.2.3 on 2023-07-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NataliyaApp', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='add_item_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='banner_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='edit_item_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='view_order_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='role',
            field=models.CharField(blank=True, choices=[('user1', 'Staff'), ('user2', 'User')], max_length=255, null=True),
        ),
    ]
