# Generated by Django 4.2.3 on 2023-07-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NataliyaApp', '0004_alter_item_category_alter_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('Wrap', 'Wrap'), ('Icecreem', 'Iceceem'), ('Shake', 'Shake')], max_length=255, null=True),
        ),
    ]
