# Generated by Django 4.2.3 on 2023-07-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NataliyaApp', '0006_alter_item_image2_alter_item_image3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.FileField(default='static/images/default.png', upload_to='images/category-banner')),
            ],
        ),
        migrations.RenameField(
            model_name='item',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image4',
        ),
        migrations.AlterField(
            model_name='item',
            name='offer',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
