# Generated by Django 4.2.3 on 2023-08-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NataliyaApp', '0008_item_title_description_alter_item_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='banner_images/')),
                ('label_1', models.CharField(max_length=100)),
                ('image_2', models.ImageField(upload_to='banner_images/')),
                ('label_2', models.CharField(max_length=100)),
                ('image_3', models.ImageField(upload_to='banner_images/')),
                ('label_3', models.CharField(max_length=100)),
                ('image_4', models.ImageField(upload_to='banner_images/')),
                ('label_4', models.CharField(max_length=100)),
                ('image_5', models.ImageField(upload_to='banner_images/')),
                ('label_5', models.CharField(max_length=100)),
            ],
        ),
    ]
